- name: Stop iptables
  service: name=iptables state=stopped enabled=no
  ignore_errors: yes

- name: Stop iptables for CentOS 7
  service: name=firewalld state=stopped enabled=no
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  ignore_errors: yes

- name: Stop selinux
  raw: /usr/sbin/setenforce 0
  ignore_errors: yes

- name: Disable selinux
  shell: sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux

- name: Disable selinux
  shell: sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
