- name: Stop iptables 
  service: name=iptables state=stopped enabled=no
  ignore_errors: yes

- name: Stop iptables for CentOS 7
  service: name=firewalld state=stopped enabled=no
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  ignore_errors: yes

- name: Stop selinux
  raw: /usr/sbin/setenforce 0 
  ignore_errors: yes

- name: Disable selinux
  shell: sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux

- name: Install zabbix_agents packge
  yum: name=zabbix_agents-3.0 state=latest

- name: Ensure directory exists
  file: path={{ item }} state=directory owner=zabbix group=zabbix
  with_items:
    - /data/logs/zabbix

- name: Put on the zabbix_agents conf files
  template: src={{item.src}} dest={{item.dest}} owner=root group=root mode={{item.mode}} force=yes backup=yes
  with_items:
    - { src: 'zabbix_agentd.conf', dest: '/usr/local/zabbix_agents/conf/zabbix_agentd.conf', mode: 644 }

- name: start zabbix
  command: /usr/local/zabbix_agents/sbin/zabbix_agentd -c /usr/local/zabbix_agents/conf/zabbix_agentd.conf

- name: rc.locl
  shell: echo "/usr/local/zabbix_agents/sbin/zabbix_agentd -c /usr/local/zabbix_agents/conf/zabbix_agentd.conf" >> /etc/rc.local
